// Code generated by tools/gen-services from botocore 1.43.45; DO NOT EDIT.
//
// Source: https://github.com/boto/botocore/tree/1.43.45/botocore/data
// Regenerate with: go generate ./...

package main

import "regexp"

// generatedServiceAliases maps single-label endpoint host labels whose SigV4
// signing name differs from the label itself (service model endpointPrefix vs
// signingName).
var generatedServiceAliases = map[string]string{
	"agreement-marketplace":           "aws-marketplace",
	"appconfigdata":                   "appconfig",
	"appstream2":                      "appstream",
	"bedrock-agent":                   "bedrock",
	"bedrock-agent-runtime":           "bedrock",
	"bedrock-agentcore-control":       "bedrock-agentcore",
	"bedrock-data-automation":         "bedrock",
	"bedrock-data-automation-runtime": "bedrock",
	"bedrock-runtime":                 "bedrock",
	"cassandra-streams":               "cassandra",
	"cloudhsmv2":                      "cloudhsm",
	"cloudsearchdomain":               "cloudsearch",
	"contact-lens":                    "connect",
	"data-signer":                     "signer",
	"deployment-marketplace":          "aws-marketplace",
	"discovery-marketplace":           "aws-marketplace",
	"email":                           "ses",
	"forecastquery":                   "forecast",
	"identity-chime":                  "chime",
	"ivsrealtime":                     "ivs",
	"mail-manager":                    "ses",
	"media-pipelines-chime":           "chime",
	"meetings-chime":                  "chime",
	"memory-db":                       "memorydb",
	"messaging-chime":                 "chime",
	"migrationhub-config":             "mgh",
	"models-v2-lex":                   "lex",
	"oidc":                            "sso-oauth",
	"partnercentral-prm":              "partnercentral",
	"personalize-events":              "personalize",
	"personalize-runtime":             "personalize",
	"pinpoint":                        "mobiletargeting",
	"reporting-marketplace":           "aws-marketplace",
	"runtime-v2-lex":                  "lex",
	"s3-control":                      "s3",
	"servicecatalog-appregistry":      "servicecatalog",
	"voice-chime":                     "chime",
}

// generatedDottedAliases maps multi-label endpoint prefixes (the labels
// immediately before the region) whose signing name differs from their last
// label, e.g. participant.connect.<region>.amazonaws.com signs "execute-api".
// Prefixes under iot are excluded: proxy.go's iot rules own those hosts.
var generatedDottedAliases = map[string]string{
	"catalog.marketplace":     "aws-marketplace",
	"entitlement.marketplace": "aws-marketplace",
	"metering.marketplace":    "aws-marketplace",
	"participant.connect":     "execute-api",
	"portal.sso":              "awsssoportal",
	"sms-voice.pinpoint":      "sms-voice",
}

// generatedPartitionSuffixes maps each partition DNS suffix to the pattern
// matching its region labels. A suffix shared by several partitions (aws and
// aws-us-gov both use amazonaws.com) gets the union of their region regexps.
var generatedPartitionSuffixes = map[string]*regexp.Regexp{
	"amazonaws.com":                regexp.MustCompile(`^(?:(us|eu|ap|sa|ca|me|af|il|mx)\-\w+\-\d+|us\-gov\-\w+\-\d+)$`),
	"amazonaws.com.cn":             regexp.MustCompile(`^(?:cn\-\w+\-\d+)$`),
	"amazonaws.eu":                 regexp.MustCompile(`^(?:eusc\-(de)\-\w+\-\d+)$`),
	"api.amazonwebservices.com.cn": regexp.MustCompile(`^(?:cn\-\w+\-\d+)$`),
	"api.amazonwebservices.eu":     regexp.MustCompile(`^(?:eusc\-(de)\-\w+\-\d+)$`),
	"api.aws":                      regexp.MustCompile(`^(?:(us|eu|ap|sa|ca|me|af|il|mx)\-\w+\-\d+|us\-gov\-\w+\-\d+)$`),
	"c2s.ic.gov":                   regexp.MustCompile(`^(?:us\-iso\-\w+\-\d+)$`),
	"cloud.adc-e.uk":               regexp.MustCompile(`^(?:eu\-isoe\-\w+\-\d+)$`),
	"csp.hci.ic.gov":               regexp.MustCompile(`^(?:us\-isof\-\w+\-\d+)$`),
	"sc2s.sgov.gov":                regexp.MustCompile(`^(?:us\-isob\-\w+\-\d+)$`),
}

// generatedGlobalEndpoints lists region-less global endpoints (host labels
// before the partition suffix, exact match) with the fixed credential scope
// they sign against.
var generatedGlobalEndpoints = map[string]map[string]awsService{
	"amazonaws.com": {
		"budgets":        {signingName: "budgets", signingRegion: "us-east-1"},
		"cloudfront":     {signingName: "cloudfront", signingRegion: "us-east-1"},
		"global.health":  {signingName: "health", signingRegion: "us-east-1"},
		"iam":            {signingName: "iam", signingRegion: "us-east-1"},
		"iam.us-gov":     {signingName: "iam", signingRegion: "us-gov-west-1"},
		"route53":        {signingName: "route53", signingRegion: "us-east-1"},
		"route53.us-gov": {signingName: "route53", signingRegion: "us-gov-west-1"},
		"savingsplans":   {signingName: "savingsplans", signingRegion: "us-east-1"},
		"sts":            {signingName: "sts", signingRegion: "us-east-1"},
		"waf":            {signingName: "waf", signingRegion: "us-east-1"},
	},
	"amazonaws.com.cn": {
		"budgets":       {signingName: "budgets", signingRegion: "cn-northwest-1"},
		"global.health": {signingName: "health", signingRegion: "cn-northwest-1"},
		"route53":       {signingName: "route53", signingRegion: "cn-northwest-1"},
	},
	"c2s.ic.gov": {
		"budgets": {signingName: "budgets", signingRegion: "us-iso-east-1"},
		"route53": {signingName: "route53", signingRegion: "us-iso-east-1"},
	},
	"cloud.adc-e.uk": {
		"budgets.global": {signingName: "budgets", signingRegion: "eu-isoe-west-1"},
		"route53":        {signingName: "route53", signingRegion: "eu-isoe-west-1"},
		"savingsplans":   {signingName: "savingsplans", signingRegion: "eu-isoe-west-1"},
	},
	"csp.hci.ic.gov": {
		"budgets.global": {signingName: "budgets", signingRegion: "us-isof-south-1"},
		"route53":        {signingName: "route53", signingRegion: "us-isof-south-1"},
		"savingsplans":   {signingName: "savingsplans", signingRegion: "us-isof-south-1"},
	},
	"sc2s.sgov.gov": {
		"budgets.global": {signingName: "budgets", signingRegion: "us-isob-east-1"},
		"route53":        {signingName: "route53", signingRegion: "us-isob-east-1"},
	},
}
